export const products = [
  {
    id: 1,
    name: "Produk A",
    category: "Elektronik",
    price: 100000,
    description: "Deskripsi produk A",
    image: "/images/product1.jpg",
  },
  {
    id: 2,
    name: "Produk B",
    category: "Pakaian",
    price: 200000,
    description: "Deskripsi produk B",
    image: "/images/product2.jpg",
  },
  {
    id: 3,
    name: "Produk C",
    category: "Elektronik",
    price: 300000,
    description: "Deskripsi produk C",
    image: "/images/product3.jpg",
  },
  {
    id: 4,
    name: "Produk D",
    category: "Makanan",
    price: 50000,
    description: "Deskripsi produk D",
    image: "/images/product4.jpg",
  },
  {
    id: 5,
    name: "Produk E",
    category: "Pakaian",
    price: 150000,
    description: "Deskripsi produk E",
    image: "/images/product5.jpg",
  },
  {
    id: 6,
    name: "Produk F",
    category: "Elektronik",
    price: 250000,
    description: "Deskripsi produk F",
    image: "/images/product6.jpg",
  },
];
