export const transactions = [
  {
    id: 1,
    user: "user123",
    product: {
      id: 1,
      name: "Produk A",
      category: "Elektronik",
      price: 100000,
      description: "Deskripsi produk A",
      image: "/images/product1.jpg",
    },
    date: "2023-04-15",
    totalAmount: 100000,
    status: "Selesai",
  },
  {
    id: 2,
    user: "user123",
    product: {
      id: 2,
      name: "Produk B",
      category: "Pakaian",
      price: 200000,
      description: "Deskripsi produk B",
      image: "/images/product2.jpg",
    },
    date: "2023-04-16",
    totalAmount: 200000,
    status: "Menunggu Pembayaran",
  },
  {
    id: 3,
    user: "user123",
    product: {
      id: 3,
      name: "Produk C",
      category: "Elektronik",
      price: 300000,
      description: "Deskripsi produk C",
      image: "/images/product3.jpg",
    },
    date: "2023-04-17",
    totalAmount: 300000,
    status: "Selesai",
  },
];
